// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project33_WebApiActionMethods.Data;

#nullable disable

namespace Project33_WebApiActionMethods.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251106162358_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Project33_WebApiActionMethods.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "6.1 inç Super Retina XDR ekranlı, A16 Bionic çipli akıllı telefon",
                            Name = "Apple iPhone 15",
                            Price = 49999m
                        },
                        new
                        {
                            Id = 2,
                            Description = "4K UHD çözünürlük, HDR10+ destekli 55 inç akıllı televizyon",
                            Name = "Samsung 55'' QLED TV",
                            Price = 29999m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lazerli kablosuz dik süpürge, güçlü emiş gücü ve toz algılama teknolojisi",
                            Name = "Dyson V15 Detect",
                            Price = 25999m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Gürültü engelleyici kablosuz kulaklık, yüksek çözünürlüklü ses desteği",
                            Name = "Sony WH-1000XM5",
                            Price = 14999m
                        },
                        new
                        {
                            Id = 5,
                            Description = "14'' ekran, AMD Ryzen 9 işlemci, RTX 4060 ekran kartlı gaming laptop",
                            Name = "Asus ROG Zephyrus G14",
                            Price = 64999m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Hava taban teknolojili spor ayakkabı, konfor ve stil bir arada",
                            Name = "Nike Air Max 270",
                            Price = 4999m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Yağsız fritöz, sıcak hava teknolojisiyle sağlıklı kızartmalar",
                            Name = "Philips Airfryer XXL",
                            Price = 8999m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Darbeye dayanıklı, su geçirmez analog-dijital kol saati",
                            Name = "Casio G-Shock GA-2100",
                            Price = 3999m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Ergonomik kablosuz mouse, sessiz tıklama ve hızlı şarj desteği",
                            Name = "Logitech MX Master 3S",
                            Price = 3299m
                        },
                        new
                        {
                            Id = 10,
                            Description = "6.8 inç aydınlatmalı e-kitap okuyucu, suya dayanıklı tasarım",
                            Name = "Kindle Paperwhite 11. Nesil",
                            Price = 5999m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
