// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project29_Repository_Design_Pattern_Sample.Data;

#nullable disable

namespace Project29_Repository_Design_Pattern_Sample.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251104163316_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Project29_Repository_Design_Pattern_Sample.Data.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Name = "Kurs 1"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Kurs 2"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Kurs 3"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Kurs 4"
                        });
                });

            modelBuilder.Entity("Project29_Repository_Design_Pattern_Sample.Data.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Öğrenci 1"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Öğrenci 2"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Öğrenci 3"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Öğrenci 4"
                        });
                });

            modelBuilder.Entity("Project29_Repository_Design_Pattern_Sample.Data.Entities.StudentCourse", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentCourses");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            CourseId = 101
                        },
                        new
                        {
                            StudentId = 1,
                            CourseId = 102
                        },
                        new
                        {
                            StudentId = 1,
                            CourseId = 103
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 101
                        },
                        new
                        {
                            StudentId = 3,
                            CourseId = 102
                        },
                        new
                        {
                            StudentId = 3,
                            CourseId = 103
                        },
                        new
                        {
                            StudentId = 4,
                            CourseId = 103
                        },
                        new
                        {
                            StudentId = 4,
                            CourseId = 104
                        },
                        new
                        {
                            StudentId = 4,
                            CourseId = 102
                        });
                });

            modelBuilder.Entity("Project29_Repository_Design_Pattern_Sample.Data.Entities.StudentCourse", b =>
                {
                    b.HasOne("Project29_Repository_Design_Pattern_Sample.Data.Entities.Course", "Course")
                        .WithMany("StudentCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project29_Repository_Design_Pattern_Sample.Data.Entities.Student", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Project29_Repository_Design_Pattern_Sample.Data.Entities.Course", b =>
                {
                    b.Navigation("StudentCourses");
                });

            modelBuilder.Entity("Project29_Repository_Design_Pattern_Sample.Data.Entities.Student", b =>
                {
                    b.Navigation("StudentCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
